In [11]:
import numpy as np

## DATA IMPORT -------------------------------------------------------------------------------------------------------------------
data_dir = '../data/raw/'
filename = 'g14.txt'
import_dir = data_dir + filename

# Load the first row to get the number of points and edges
header = np.loadtxt(import_dir, max_rows=1, dtype=int)

# Extract the number of points and edges from the header
npoints = header[0]
nedges = header[1]

# Load the data regarding points connected with edges and their weights (skip the first row)
data_import = np.loadtxt(import_dir, usecols=(0, 1, 2), dtype=int, skiprows=1)

# Extract edges data
edges = data_import  # This will contain all edges and their weights

# Define the number of edges you want to keep
desired_nedges = 2000  # Change this to your desired number of edges

# Reduce the edges to the desired number
if desired_nedges < len(edges):
    reduced_edges = edges[:desired_nedges]
else:
    reduced_edges = edges  # Keep all edges if desired_nedges is greater

# Update the number of edges
new_nedges = reduced_edges.shape[0]

# Update the number of points
new_npoints = int(max(reduced_edges[:, 0].max(), reduced_edges[:, 1].max()))

# Create the updated dataset
# The first row should contain the number of points and edges, but we need to keep the structure
# of the subsequent rows. We can create a new array with the same number of columns as reduced_edges.
# Here, we will create a new header row with dummy values for the points and weights.
header_row = np.array([[new_npoints, new_nedges, 0]])  # Dummy weight for the header

# Combine the header with the reduced edges
updated_data = np.vstack((header_row, reduced_edges))

# Define the output file path
output_file = f"{import_dir}{desired_nedges}.txt"  # File name with desired_nedges

# Save the updated dataset to a file
np.savetxt(output_file, updated_data, fmt='%d', delimiter=' ', comments='')

# Print the updated dataset
print("Updated Dataset:")
print(updated_data)
print(f"Data saved to {output_file}")

Updated Dataset:
[[ 800 2000    0]
 [   1    7    1]
 [   1   10    1]
 ...
 [  56  469    1]
 [  56  608    1]
 [  56  613    1]]
Data saved to ../data/raw/g14.txt2000.txt
